const express = require('express');
const app = express();
app.use(express.json());
const cart = require('./api/cart');
app.use('/cart', cart);
console.log("cart ran");
const checkout = require('./api/checkout');
app.use('/checkout', checkout);
console.log("checkout ran");
const getAllItems = require('./api/getAll');
app.use('/getAll', getAllItems);
console.log("getAll ran");
const login = require('./api/login');
app.use('/login', login);
console.log("login ran");
const postAll = require('./api/postAll');
app.use('/postAll', postAll);
console.log("postAll ran");
const update = require('./api/update');
app.use('/update', update);
console.log("update ran");
const webhook = require('./api/webhook');
app.use('/webhook', webhook);
console.log("webhook ran");

module.exports = app;
