name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build frontend (if applicable)
        run: npm run build

      - name: Deploy to EC2
        run: |
          ssh -i "imp_key.pem" ec2-user@ec2-65-1-165-105.ap-south-1.compute.amazonaws.com:/home/ec2-user/BidCommerce/Frontend
          ssh -i "imp_key.pem" ec2-user@ec2-65-1-165-105.ap-south-1.compute.amazonaws.com: 'cd /home/ec2-user/BidCommerce/Frontend && pm2 restart my-backend'

